server:
  port: 8082
  servlet:
    context-path: /goodbooks
spring:
  application:
    name: bookRatingService
  datasource:
    url: jdbc:h2:mem:ratingdb
    driverClassName: org.h2.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8700/eureka/