server:
  port: 8082
  servlet:
    context-path: /goodbooks
spring:
  datasource:
    url: jdbc:h2:mem:ratingdb
    driverClassName: org.h2.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2